server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: client-service
          uri: lb://client-service
          predicates:
            - Path=/api/clients/**
        - id: bank-account-service
          uri: lb://bank-account-service
          predicates:
            - Path=/api/accounts/**
        - id: transaction-service
          uri: lb://bank-account-service
          predicates:
            - Path=/api/transactions/**
        - id: credits-service
          uri: lb://bank-account-service
          predicates:
            - Path=/api/credits/**
        - id: reports-service
          uri: lb://bank-account-service
          predicates:
            - Path=/api/reports/**
